name: Create PR from devel to main
on:
  push:
    branches:
      - devel
jobs:
  gitPrRelease:
    name: git-pr-release
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: add safe directory
      run: |
        git config --global --add safe.directory $(pwd)
        echo $(pwd)
      working-directory: ./test-release
    - name: git-pr-release
      uses: bakunyo/git-pr-release-action@v1.3
      env:
        GIT_PR_RELEASE_BRANCH_STAGING: devel
        GIT_PR_RELEASE_BRANCH_PRODUCTION: main
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
