name: Create Release

on:
  push:
    tags:
      - v*
      - !*.rc*
      - !*.b*

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
