name: Create Release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'release/*'
    types:
      - closed

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git tag $GITHUB_REF_NAME
          git push origin $GITHUB_REF_NAME
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          name: $GITHUB_REF_NAME
