name: Create Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Create release
    # https://github.com/orgs/community/discussions/25216
    # if: contains(github.ref, 'release')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git tag $GITHUB_REF_NAME
          git push origin $GITHUB_REF_NAME
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          name: $GITHUB_REF_NAME
