name: Create Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Create release
    if: github.head_ref == "release" || github.head_ref == "hotfix"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Extract version
        id: extract_version
        run: |
          echo "version=${GITHUB_HEAD_REF##*/}" >> $GITHUB_OUTPUT
      - name: Create tag
        id: create_tag
        run: |
          git tag ${{ steps.extract_version.outputs.version }}
          git push origin ${{ steps.extract_version.outputs.version }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          name: ${{ steps.extract_version.outputs.version }}
          tag_name: ${{ steps.extract_version.outputs.version }}
